// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from '@tanstack/react-start'
import { getRequest } from '@tanstack/react-start/server'
import { createClient } from '@supabase/supabase-js'
import type { Database } from './types'

function validateOrigin(request: Request): void {
  const origin = request.headers.get('origin');
  const referer = request.headers.get('referer');

  // Browsers always send Origin or Referer for cross-origin requests.
  // If both are absent, this is likely a direct API call (curl, fetch from server) — allow.
  if (!origin && !referer) return;

  const ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    'breezkit.app',
    'breezkit.vercel.app',
    'breezkit.netlify.app',
  ];

  const source = origin ?? referer!;
  try {
    const url = new URL(source);
    const hostname = url.hostname;

    // Allow localhost in any port for development
    if (hostname === 'localhost' || hostname === '127.0.0.1') return;

    const allowed = ALLOWED_HOSTS.some(
      (h) => hostname === h || hostname.endsWith(`.${h}`),
    );

    if (!allowed) {
      const err = new Error(`Unauthorized: Request origin not allowed (${hostname})`);
      (err as any).statusCode = 403;
      throw err;
    }
  } catch {
    const err = new Error('Unauthorized: Invalid origin header');
    (err as any).statusCode = 403;
    throw err;
  }
}

export const requireSupabaseAuth = createMiddleware({ type: 'function' }).server(
  async ({ next }) => {
    
    const SUPABASE_URL = process.env.SUPABASE_URL;
    const SUPABASE_PUBLISHABLE_KEY = process.env.SUPABASE_PUBLISHABLE_KEY || process.env.SUPABASE_ANON_KEY;

    if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
      const missing = [
        ...(!SUPABASE_URL ? ['SUPABASE_URL'] : []),
        ...(!SUPABASE_PUBLISHABLE_KEY ? ['SUPABASE_PUBLISHABLE_KEY'] : []),
      ];
      const message = `Missing Supabase environment variable(s): ${missing.join(', ')}. Connect Supabase in Lovable Cloud.`;
      console.error(`[Supabase] ${message}`);
      throw new Error(message);
    }
    
    const request = getRequest();

    if (!request?.headers) {
      const err = new Error('Unauthorized: No request headers available');
      (err as any).statusCode = 401;
      throw err;
    }

    validateOrigin(request);

    const authHeader = request.headers.get('authorization');

    if (!authHeader) {
      const err = new Error('Unauthorized: No authorization header provided');
      (err as any).statusCode = 401;
      throw err;
    }

    if (!authHeader.startsWith('Bearer ')) {
      const err = new Error('Unauthorized: Only Bearer tokens are supported');
      (err as any).statusCode = 401;
      throw err;
    }

    const token = authHeader.replace('Bearer ', '');
    if (!token) {
      const err = new Error('Unauthorized: No token provided');
      (err as any).statusCode = 401;
      throw err;
    }

    const supabase = createClient<Database>(
      SUPABASE_URL!,
      SUPABASE_PUBLISHABLE_KEY!,
      {
        global: {
          headers: {
            Authorization: `Bearer ${token}`,
          },
        },
        auth: {
          storage: undefined,
          persistSession: false,
          autoRefreshToken: false,
        },
      }
    );

    const { data, error } = await supabase.auth.getUser(token);
    if (error || !data?.user) {
      const err = new Error('Unauthorized: Invalid token');
      (err as any).statusCode = 401;
      throw err;
    }

    return next({
      context: {
        supabase,
        userId: data.user.id,
      },
    });
  },
);
